version: '3'

services:
    rdfacility:
            build:
                    context: .
                    dockerfile: ./dotnet
    reverseproxy:
            build:
                    context: .
                    dockerfile: ./nginx
            ports:
                    - 80:8080
            restart: always
            depends_on:
                    - rdfacility
